# Generated by Django 4.2.16 on 2025-08-09 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_food_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='user',
        ),
    ]
