# Generated by Django 4.2.16 on 2025-08-09 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='user',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='user',
        ),
    ]
