# Generated by Django 4.2.16 on 2025-06-08 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_role_user_is_created_alter_user_avatar_user_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="main_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subordinates",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Главный пользователь",
            ),
        ),
    ]
